language:
- objective-c
env:
  global: LATEST_TAG=1
  matrix:
  - VERSION=2.7.8
  - VERSION=3.3.5
  - VERSION=3.4.1
install:
- source terryfy/travis_tools.sh
- get_python_environment macpython $VERSION venv
- pip install wheel
- if [ -n "$LATEST_TAG" ]; then checkout_closest_tag Cython; fi
- cd Cython
- python setup.py bdist_wheel
- rename_wheels dist
- pip install dist/*.whl
- cd ..
script:
- cd Cython
- cython Demos/*.pyx
- cd ..
before_deploy: cd Cython/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: TX5368tmsJJsaAcizN4bn5HA/HQA5OlogfhRGTHDNOHfiCZAjhl78R1oyX7Kle3adBCv5QC305m+GaJUgIMkl+VlPdEuQhvFpShmXqOX6BMByWVojqj8qahLG/TkwUK+njFlNHST3qnRWhCaEVxAju5Sp/pg3IgaAl0GSfCWntE=
  region: ORD
  container: wheels
  skip_cleanup: true
