language:
- objective-c
env:
  global:
  - BUILD_COMMIT=latest-tag
  - REPO_DIR=cython
  matrix:
  - VERSION=2.7.10
  - VERSION=3.2.5
  - VERSION=3.3.5
  - VERSION=3.4.3
  - VERSION=3.5.0
install:
- source terryfy/travis_tools.sh
- export CC=clang
- export CXX=clang++
- get_python_environment macpython $VERSION venv
# Update to latest wheel package for Python 3.5
- pip install -U wheel
- pip install delocate
- if [ -n "$BUILD_COMMIT" ]; then
      checkout_commit $REPO_DIR $BUILD_COMMIT;
  fi
- cd $REPO_DIR
- python setup.py bdist_wheel
- delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl
- pip install dist/*.whl
- cd ..
script:
- cd $REPO_DIR
- cython Demos/*.pyx
- cd ..
before_deploy:
- cd $REPO_DIR/dist
# Fix for https://github.com/travis-ci/travis-ci/issues/4635
- rvm 1.9.3 do gem install net-ssh -v 2.9.2
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: TX5368tmsJJsaAcizN4bn5HA/HQA5OlogfhRGTHDNOHfiCZAjhl78R1oyX7Kle3adBCv5QC305m+GaJUgIMkl+VlPdEuQhvFpShmXqOX6BMByWVojqj8qahLG/TkwUK+njFlNHST3qnRWhCaEVxAju5Sp/pg3IgaAl0GSfCWntE=
  region: ORD
  container: wheels
  skip_cleanup: true
